# Generated by Django 5.0.4 on 2024-04-16 18:04

import django.core.validators
import django.db.models.deletion
import final_project.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, validators=[final_project.core.validators.validate_title_letter_number_space, django.core.validators.MinLengthValidator(2)])),
                ('genre', models.CharField(choices=[('Fantasy', 'Fantasy'), ('Science Fiction', 'Science Fiction'), ('Romance', 'Romance'), ('Mystery/Thriller', 'Mystery/Thriller'), ('Young adult', 'Young adult'), ('Non-fiction', 'Non-fiction'), ('Fiction', 'Fiction')], max_length=30)),
                ('review', models.TextField()),
                ('image', models.ImageField(upload_to='book/', validators=[final_project.core.validators.max_size_of_the_photo])),
                ('date_of_publication', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
